# PiBoat2 Boat Configuration

boat:
  id: "piboat2_002"
  name: "PiBoat2 Test Vessel"
  
mqtt:
  broker_host: "ec2-174-129-132-111.compute-1.amazonaws.com"
  broker_port: 1883
  use_tls: false
  keepalive: 60
  qos: 1
  username: "${MQTT_USERNAME}"
  password: "${MQTT_PASSWORD}"

hardware:
  gps_device: "/dev/ttyACM0"
  gps_baudrate: 9600
  gps_update_interval: 5
  
  compass_i2c_address: 0x60
  compass_calibration_file: "config/compass_calibration.json"
  
  motor_controller_device: "/dev/ttyUSB1"
  left_motor_pin: 18
  right_motor_pin: 19
  max_speed_percent: 70

navigation:
  max_speed: 50
  arrival_radius: 10.0
  max_rudder_angle: 45.0
  
safety:
  command_timeout: 30
  emergency_stop_timeout: 5
  geofence_enabled: false
  max_drift: 5.0

logging:
  level: "INFO"
  file: "/var/log/piboat2.log"
  max_size_mb: 10
  backup_count: 5

status_reporting:
  interval: 10
  include_gps: true
  include_motors: true
  include_system: true